[package]
name = "escalator-status-bot-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.67"
chrono = "0.4.23"
indexmap = { version = "1.9.2", features = ["serde"] }
itertools = "0.10.5"
lazy_static = "1.4.0"
poise = "0.5.2"
serde = { version = "1.0", features = ["derive"] }
shuttle-persist = "0.8.0"
shuttle-secrets = "0.8.0"
shuttle-service = "0.8.0"
tokio = { version = "1", features = ["full"] }

[patch.crates-io]
dashmap = { git = "https://github.com/snylonue/dashmap", branch = "no-toolchain" }
